extends SceneTree
const M=preload("res://scripts/shovel/model.gd")
const Main=preload("res://scripts/shovel/main.gd")
const D=preload("res://scripts/ea/decimal.gd")
var failures:=0
var checks:=0
func check(value: bool, message: String) -> void:
	checks+=1
	if not value: failures+=1; printerr("FAIL: "+message)
func _initialize() -> void: call_deferred("run")
func run() -> void:
	var m:=M.new()
	check(m.shovel_count==1 and m.idle_count()==1,"one idle shovel at start")
	check(m.next_shovel_price()==60,"first extra shovel costs 60")
	check(not m.buy_shovel() and m.wallet.exact()=="0","insufficient funds never deducted")
	m.wallet=D.new("59"); check(not m.buy_shovel(),"59 points insufficient")
	m.wallet=D.new("60"); check(m.buy_shovel() and m.wallet.exact()=="0" and m.idle_count()==2,"exact price adds idle shovel")
	check(m.next_shovel_price()==120,"next price rises")
	m.paused=true; m.wallet=D.new("10000")
	check(not m.buy_shovel() and not m.dispatch(Vector2(400,350)),"pause prevents purchases and dispatch")
	m.paused=false
	check(m.dispatch(Vector2(400,350)),"dispatch first unit")
	check(m.shovels[0].position==M.HUD_POINT and m.unit_scale(m.shovels[0])<1,"launch small from HUD")
	check(not m.dispatch(Vector2(400,350)) and m.idle_count()==1,"occupied target does not consume another unit")
	check(m.dispatch(Vector2(480,350)),"second unit dispatched concurrently to partially overlapping circle")
	check(not m.dispatch(Vector2(700,500)),"no third dispatch when both busy")
	var used: Dictionary={}
	var total_pixels:=0
	for unit in m.shovels:
		for p in unit.job.pixels:
			if used.has(p): check(false,"parallel jobs have disjoint pixels")
			used[p]=true; total_pixels+=1
	check(total_pixels>0,"reserved footprints exist")
	m.tick(0.15)
	check(m.shovels[0].position!=M.HUD_POINT and m.unit_scale(m.shovels[0])>0.34,"outbound flies and grows")
	var position: Vector2=m.shovels[0].position
	m.paused=true; m.tick(5); check(m.shovels[0].position==position,"pause freezes flight"); m.paused=false
	m.tick(2)
	check(m.shovels[0].phase=="digging" and m.shovels[1].phase=="digging","both units arrive")
	check(m.shovels[0].job.time==0,"travel excluded from 20 seconds")
	m.tick(10)
	check(m.layers[0].cleared==0 and float(m.earned.exact())>0,"income before clearing")
	check(m.shovels[0].job.time==10 and m.shovels[1].job.time==10,"independent timers progress concurrently")
	m.paused=true; m.tick(10); check(m.shovels[0].job.time==10,"pause freezes digging"); m.paused=false
	var save_file:="user://shovel_fleet_test.dat"
	check(m.save_to(save_file)==OK,"save two active jobs")
	var restored:=M.new(); check(restored.load_from(save_file),"load fleet")
	check(restored.shovel_count==2 and restored.shovels[1].job.time==10,"restore count and second timer")
	m.tick(9.9); check(m.layers[0].cleared==0,"soil intact before deadline")
	m.tick(0.1); restored.tick(10)
	check(m.layers[0].cleared==total_pixels,"exact union cleared once")
	check(m.layers[1].cleared==0,"no accidental second layer excavation")
	check(m.progress(0)==float(total_pixels)/M.PIXELS,"percentage matches cleared area")
	check(m.shovels[0].phase=="returning" and m.idle_count()==0,"completion begins return before reuse")
	check(m.wallet.exact()==restored.wallet.exact(),"restore cannot double-pay scrap")
	var expected:=0
	for find in m.layers[0].finds:
		if find.kind=="scrap" and find.collected: expected+=int(find.value)
	check(m.earned.exact()==str(expected),"parallel rewards equal unique collected random rewards")
	var balance:=m.wallet.exact()
	m.tick(0.3)
	check(m.unit_scale(m.shovels[0])<1 and m.shovels[0].position!=position,"return shrinks and moves")
	check(m.save_to(save_file)==OK,"save during return")
	var returning:=M.new(); check(returning.load_from(save_file),"restore return flight")
	m.tick(1); returning.tick(1)
	check(m.idle_count()==2 and returning.idle_count()==2,"return finishes to idle after reload")
	check(m.shovels[0].position==M.HUD_POINT and m.shovels[0].job.is_empty(),"returned unit lives in HUD, no ground job")
	m.tick(30); check(m.wallet.exact()==balance,"idle never repeats reward")
	check(m.dispatch(Vector2(400,350)) and m.shovels[0].job.depth==2,"next click sends idle shovel to deeper soil")
	m.tick(2); m.tick(20)
	check(m.layers[1].cleared==0 and is_equal_approx(m.shovels[0].job.duration,100),"second layer is still intact after twenty seconds")
	m.tick(80); m.tick(1)
	check(m.layers[1].cleared>0,"deeper layer can be dug")
	check(is_equal_approx(m.dig_seconds(1),20) and is_equal_approx(m.dig_seconds(2),100) and is_equal_approx(m.dig_seconds(3),500) and is_equal_approx(m.dig_seconds(4),2500),"depth duration increases fivefold")
	var mixed:=M.new(); mixed.dispatch(Vector2(500,400)); mixed.tick(2); mixed.tick(20); mixed.tick(1)
	check(mixed.surface_at(Vector2(520,400))==1,"regression setup: click center exposes second layer")
	check(mixed.dispatch(Vector2(520,400)) and mixed.shovels[0].job.depth==1,"circle's first-layer rim takes priority over center hole")
	mixed.tick(2); mixed.tick(20); mixed.tick(1)
	check(mixed.layers[1].cleared==0,"rim excavation never touches second layer")
	var occupied:=M.new(); occupied.wallet=D.new("60"); occupied.buy_shovel()
	occupied.dispatch(Vector2(500,400)); occupied.tick(2); occupied.tick(20); occupied.tick(1)
	occupied.dispatch(Vector2(520,400))
	check(not occupied.dispatch(Vector2(520,400)),"reserved upper rim blocks lower-layer dispatch")
	var sliver:=M.new()
	var disk:=sliver.circle_pixels(Vector2(500,400))
	for pixel in disk: sliver.layers[0].mask[pixel]=0; sliver.layers[0].wear[pixel]=1.0
	sliver.layers[0].cleared=disk.size()-1
	sliver.layers[0].mask[disk[0]]=255; sliver.layers[0].wear[disk[0]]=0.0
	check(sliver.dispatch(Vector2(500,400)) and sliver.shovels[0].job.depth==1 and sliver.shovels[0].job.pixels.size()==1,"even one top-layer pixel prevents bypass")
	m.scratch(Vector2(800,650),Vector2(900,700),10)
	check(m.layers[0].cleared==total_pixels,"legacy scratching disabled")
	check(not m.buy("opening") and not m.buy_machine(0) and not m.buy_analyzer() and not m.buy_talent("T00"),"all old upgrades blocked")
	m.wallet=D.new("100000")
	var old_price:=m.next_shovel_price()
	while m.shovel_count<10:
		check(m.next_shovel_price()>=old_price,"monotonic prices")
		old_price=m.next_shovel_price(); check(m.buy_shovel(),"purchase next shovel")
	balance=m.wallet.exact(); check(not m.buy_shovel() and m.wallet.exact()==balance and m.shovels.size()==10,"hard cap with no extra debit")
	var ten:=M.new(); ten.wallet=D.new("100000")
	while ten.shovel_count<10: ten.buy_shovel()
	for y in [220,600]:
		for x in [120,300,480,660,840]: check(ten.dispatch(Vector2(x,y)),"dispatch ten workers")
	ten.tick(2); ten.tick(20)
	check(ten.layers[0].cleared>0 and ten.idle_count()==0,"ten workers complete and return")
	ten.tick(1); check(ten.idle_count()==10,"all ten back in stock")
	var edge:=M.new(); check(edge.dispatch(Vector2(0,0)),"edge dispatch clips safely")
	var upgrades:=M.new()
	check(upgrades.power_price().exact()=="100" and upgrades.range_price().exact()=="200","upgrade starting costs")
	check(not upgrades.buy_power() and not upgrades.buy_range(),"unaffordable upgrades do not apply")
	upgrades.wallet=D.new("10000"); upgrades.buy_shovel(); upgrades.dispatch(Vector2(350,300))
	var old_duration: float=upgrades.shovels[0].job.duration
	check(upgrades.buy_power() and upgrades.buy_range(),"buy shared strength and radius")
	check(is_equal_approx(upgrades.dig_seconds(1),20.0/1.2) and is_equal_approx(upgrades.dig_seconds(2),100.0/1.2),"strength multiplies speed by 1.2")
	check(is_equal_approx(upgrades.dig_radius(),72*1.1),"radius grows by ten percent")
	check(upgrades.shovels[0].job.duration==old_duration and upgrades.shovels[0].job.radius==72,"existing moving job retains size and duration")
	upgrades.dispatch(Vector2(750,550))
	check(is_equal_approx(upgrades.shovels[1].job.duration,20.0/1.2) and is_equal_approx(upgrades.shovels[1].job.radius,79.2),"new job receives both upgrades")
	var area_ratio: float=float(upgrades.shovels[1].job.pixels.size())/upgrades.shovels[0].job.pixels.size()
	check(absf(area_ratio-1.21)<0.01,"radius increase produces 21 percent larger footprint")
	upgrades.tick(2); upgrades.tick(5); upgrades.save_to(save_file)
	var upgraded_load:=M.new(); check(upgraded_load.load_from(save_file),"reload upgraded fleet")
	check(upgraded_load.power_level==1 and upgraded_load.range_level==1,"upgrade levels persisted")
	check(upgraded_load.shovels[0].job.duration==old_duration and upgraded_load.shovels[0].job.radius==72,"old-job snapshot survives reload after upgrades")
	var prices:=M.new(); prices.wallet=D.new("100000")
	for price in [100,180,320,580,1050]:
		check(prices.power_price().exact()==str(price),"strength price progression")
		prices.buy_power()
	for price in [200,320,510,820,1310]:
		check(prices.range_price().exact()==str(price),"range price progression")
		prices.buy_range()
	var before_cap:=prices.wallet.exact()
	check(not prices.buy_range() and prices.wallet.exact()==before_cap,"radius cap prevents extra charges")
	check(is_equal_approx(prices.dig_radius(),72*pow(1.1,5)),"fifth radius level")
	prices.power_level=20
	check(prices.dig_seconds(1)==2.0,"two-second minimum duration")
	prices.paused=true; check(not prices.buy_power(),"pause blocks strength upgrades")
	var wider:=M.new(); wider.dispatch(Vector2(500,400)); wider.tick(2); wider.tick(20); wider.tick(1)
	wider.wallet=D.new("200"); wider.buy_range()
	check(wider.dispatch(Vector2(500,400)) and wider.shovels[0].job.depth==1,"enlarged circle cleans newly included upper rim first")
	var legacy:=M.new(); legacy.dispatch(Vector2(550,420)); legacy.tick(2); legacy.tick(7)
	legacy.save_to(save_file)
	var file:=FileAccess.open(save_file,FileAccess.READ); var state: Dictionary=file.get_var(); file.close()
	state.erase("shovels"); state.shovel_job=legacy.shovels[0].job.duplicate(true); state.shovel_job.phase="digging"
	state.shovel_job.erase("duration")
	state.shovel_position=Vector2(550,420)
	file=FileAccess.open(save_file,FileAccess.WRITE); file.store_var(state); file.close()
	var migrated:=M.new(); check(migrated.load_from(save_file),"load old single-shovel save")
	check(migrated.shovels[0].phase=="digging" and migrated.shovels[0].job.time==7,"migrate legacy progress")
	migrated.tick(13); migrated.tick(1); check(migrated.idle_count()==1,"migrated unit completes and returns")
	var recalled:=M.new(); var baseline:=M.new()
	var target:=Vector2(500,400)
	recalled.dispatch(target); baseline.dispatch(target)
	recalled.tick(2); recalled.tick(10)
	var partial_money:=recalled.wallet.exact()
	check(float(partial_money)>0,"earned points before recall")
	recalled.paused=true; check(not recalled.recall(0),"pause blocks recall"); recalled.paused=false
	check(recalled.recall(0) and recalled.shovels[0].phase=="returning","recall starts return animation")
	check(recalled.shovels[0].job.is_empty() and recalled.layers[0].cleared==0,"recall discards progress and leaves soil intact")
	check(recalled.wallet.exact()==partial_money,"recall keeps points already earned")
	check(not recalled.recall(0),"cannot recall returning unit twice")
	recalled.save_to(save_file)
	var recalled_load:=M.new(); check(recalled_load.load_from(save_file),"load recalled return")
	recalled_load.tick(1)
	check(recalled_load.dispatch(target),"recalled reservations released")
	check(recalled_load.shovels[0].job.time==0,"same target restarts at zero")
	recalled_load.tick(2); recalled_load.tick(19.9)
	check(recalled_load.layers[0].cleared==0,"retry requires full twenty seconds")
	recalled_load.tick(0.1); baseline.tick(2); baseline.tick(20)
	check(recalled_load.wallet.exact()==baseline.wallet.exact(),"recall/retry cannot farm duplicate rewards")
	var outbound:=M.new(); outbound.dispatch(target); outbound.tick(0.1)
	var initial_scale:=outbound.unit_scale(outbound.shovels[0])
	check(outbound.recall(0) and is_equal_approx(outbound.unit_scale(outbound.shovels[0]),initial_scale),"mid-flight recall preserves scale")
	check(outbound.wallet.exact()=="0","recall before digging earns nothing")
	DirAccess.remove_absolute(save_file)
	var game:=Main.new(); root.add_child(game); game.save_enabled=false; game.set_process(false); game._start_new_game()
	var random_rewards:=M.new()
	var gold_count:=0; var invalid:=0; var regular_counts:=[0,0,0,0,0]
	var terrain_rng_before: int=random_rewards.rng.state
	for id in range(1,10001):
		var find:={"id":id,"value":1}
		var first_reward: String=random_rewards.scrap_reward(random_rewards.layers[0],find).exact()
		if first_reward!=random_rewards.scrap_reward(random_rewards.layers[0],find).exact(): invalid+=1
		var value:=int(first_reward)
		if value==10: gold_count+=1
		elif value in [1,2,3,4,5]: regular_counts[value-1]+=1
		else: invalid+=1
	check(invalid==0,"rewards stay in 1-5 or 10 and never reroll")
	check(gold_count>=150 and gold_count<=250,"gold probability near two percent in 10000 samples")
	check(regular_counts.min()>1700 and regular_counts.max()<2200,"normal values approximately uniform")
	check(random_rewards.rng.state==terrain_rng_before,"reward RNG leaves terrain generation unchanged")
	var deep_find:={"id":912,"value":1}
	var shallow_find:=deep_find.duplicate()
	var deep_layer:=random_rewards.layers[0].duplicate(); deep_layer.scale=D.new("1000000").data()
	check(random_rewards.scrap_reward(deep_layer,deep_find).exact()==random_rewards.scrap_reward(random_rewards.layers[0],shallow_find).exact(),"point popups do not multiply by depth")
	game.model.recent_finds.append({"kind":"scrap","position":Vector2(400,400),"text":"+10","premium":true})
	game.model.recent_finds.append({"kind":"scrap","position":Vector2(450,400),"text":"+3","premium":false})
	game.board.consume_find_events()
	check(game.board.pickup_numbers[0].font_size==28 and game.board.pickup_numbers[1].font_size==18,"gold reward font larger than normal")
	check(game.board.pickup_numbers[0].color==Color("ffd44f"),"rare ten is gold")
	var popup_start: Vector2=game.board.pickup_numbers[0].p
	game.board.step(0.1)
	check(game.board.pickup_numbers[0].p.y<popup_start.y and game.board.pickup_numbers[0].life<0.95,"old collection popup moves up and expires")
	print("REWARD SAMPLE: %d gold / 10000"%gold_count)
	check(game.shovel_icon.texture!=null and game.shovel_label.text.contains("1 / 1"),"HUD icon and idle/total")
	check(game.shovel_icon.size==Vector2(30,48),"HUD icon stays within small slot")
	check(game.shop_buttons.is_empty() and game.machine_buttons.is_empty(),"old upgrade cards not constructed")
	check(game.power_button!=null and game.range_button!=null,"new upgrade cards exist")
	game.open_page("talents"); check(game.view=="","old talents cannot open")
	game.model.wallet=D.new("60"); game._buy_shovel(); check(game.model.shovel_count==2,"shop button purchases")
	for point in [Vector2(400,350),Vector2(700,550)]:
		var click:=InputEventMouseButton.new(); click.button_index=MOUSE_BUTTON_LEFT; click.pressed=true; click.position=point; game.board._gui_input(click)
	game.model.tick(2); game.model.tick(10); game.board.step(0.04); game._refresh()
	check(game.board.crack_planes.size()==2 and game.board.crack_planes[0].visible and game.board.crack_planes[1].visible,"separate crack layers for both shovels")
	check(game.shovel_label.text.contains("0 / 2"),"HUD reflects all busy")
	var shovel_click:=InputEventMouseButton.new(); shovel_click.button_index=MOUSE_BUTTON_LEFT; shovel_click.pressed=true
	shovel_click.position=game.model.unit_draw_position(game.model.shovels[0])
	check(game.board.shovel_at(shovel_click.position)==0,"hit test follows bouncing shovel")
	game.board._gui_input(shovel_click)
	check(game.model.shovels[0].phase=="returning" and game.model.shovels[1].phase=="digging","sprite click recalls only selected shovel")
	check(not game.board.crack_planes[0].visible and game.board.crack_planes[1].visible,"recall immediately hides only its crack overlay")
	game.model.tick(10); game.model.tick(1); game.board.step(0.04); game._refresh()
	check(not game.board.crack_planes[0].visible and game.shovel_label.text.contains("2 / 2"),"cracks disappear, HUD restocks")
	game.queue_free(); await process_frame
	print("SHOVEL FLEET: %d checks, %d failures"%[checks,failures]); quit(1 if failures else 0)
