extends SceneTree
const M=preload("res://scripts/ea/model.gd")
const C=preload("res://scripts/ea/config.gd")
const D=preload("res://scripts/ea/decimal.gd")
var failures:=0
func check(value: bool,label: String) -> void:
	if not value: failures+=1; printerr("FAIL: "+label)
func _initialize() -> void: call_deferred("run")
func set_area(m: RefCounted,index: int,fraction: float) -> void:
	var layer: Dictionary=m.layers[index]
	layer.mask.fill(255); layer.wear.fill(0)
	layer.cleared=int(M.PIXELS*fraction)
	for i in range(layer.cleared): layer.mask[i]=0; layer.wear[i]=1.0
func run() -> void:
	for depth in [1,2,3,100,1000]:
		check(C.efficiency(depth-1,depth)==1.0,"adapted efficiency depth "+str(depth))
		check(is_equal_approx(C.efficiency(depth-2,depth),0.001),"one level short")
		check(is_equal_approx(C.efficiency(depth-3,depth),0.000001),"two levels short")
		check(C.efficiency(depth,depth)==4.0,"old soil easy")
	check(C.efficiency(0,1000)>0 and C.efficiency(0,1000)<1e-290,"tiny unplayable tail")
	var m:=M.new()
	m.scratch(Vector2(400,300),Vector2(400,300),0.3)
	check(m.layers[0].cleared>0 and m.layers[1].cleared==0,"no excess through damage")
	for i in range(30): m.scratch(Vector2(400,300),Vector2(400,300),0.1)
	check(m.layers[1].cleared==0,"next layer stays hard")
	m.levels.power=1
	for i in range(4): m.scratch(Vector2(400,300),Vector2(400,300),0.1)
	check(m.layers[1].cleared>0 and m.layers[2].cleared==0,"upgrade shifts adapted layer")
	var threshold:=M.new()
	set_area(threshold,0,0.9799); threshold.scan_exposed_finds()
	check(threshold.layers[0].cleared<M.PIXELS and threshold.progress_text(0)=="97.9%","97.99 does not finish")
	set_area(threshold,0,0.98001); threshold.scan_exposed_finds()
	check(threshold.layers[0].cleared==M.PIXELS and threshold.wallet.exact()=="870" and threshold.records.size()==8,"98 clears all and pays final drops")
	threshold.scan_exposed_finds()
	check(threshold.wallet.exact()=="870","no repeated threshold rewards")
	check(threshold.layers[1].cleared==0,"threshold no lower-layer damage")
	threshold.advance_layers()
	check(threshold.base_depth==2 and threshold.layers.size()==5,"rolling five layers")
	var r:Dictionary=threshold.records[0]
	check(threshold.unknown_title(r)=="未知土块","unknown title")
	check(threshold.machine_reason(0)=="先鉴定或分析本系列","raw find does not unlock series machine")
	var item_value:RefCounted=threshold.amount(r.estimate)
	check(item_value.compare(D.new("24"))>=0 and item_value.compare(D.new("36"))<=0,"variant-specific price anchor")
	threshold.wallet=D.new("10000")
	check(threshold.buy_analyzer() and threshold.unknown_title(r).contains("潜在系列"),"analyzer reveals series")
	check(not threshold.buy_analyzer(),"no repeat analyzer charge")
	check(threshold.machine_reason(0)=="","analysis unlocks matching machine")
	check(threshold.discovered.is_empty(),"analysis does not discover")
	threshold.claim_manual(int(r.id))
	threshold.add_cleaning(int(r.id),0.9799)
	check(r.step==0,"stage before threshold")
	threshold.add_cleaning(int(r.id),0.0001)
	check(r.step==1 and r.progress[0]==1.0,"first stage threshold")
	check(threshold.sale_price(r).exact()==item_value.times(70,2).floor_value().exact() and not threshold.sell(int(r.id)),"stage1 value but no sale")
	threshold.add_cleaning(int(r.id),0.98)
	check(r.status=="identified" and not r.quality and threshold.knowledge==1,"stage2 identifies without polishing")
	check(threshold.sale_price(r).exact()==item_value.floor_value().exact(),"100 percent sale")
	threshold.identify(r); check(threshold.knowledge==1,"discovery idempotent")
	threshold.polish(int(r.id),7.839)
	check(not r.quality,"polish below threshold")
	threshold.polish(int(r.id),0.002)
	check(r.quality and threshold.sale_price(r).exact()==item_value.times(125,2).floor_value().exact(),"polish125 percent")
	var stored:String=threshold.sale_price(r).exact()
	threshold.polish(int(r.id),100)
	check(threshold.sale_price(r).exact()==stored,"no compound markup")
	var budget:=M.new(); budget.wallet=D.new("199")
	check(not budget.buy("radius") and budget.wallet.exact()=="199","reserve blocks spending")
	budget.wallet=D.new("200")
	check(budget.buy("radius") and budget.wallet.exact()=="120","reserve exact boundary")
	check(budget.buy("power") and budget.wallet.exact()=="0","strength can spend reserve")
	var workers:=M.new()
	set_area(workers,0,1.0); workers.scan_exposed_finds()
	workers.machines[0].owned=true
	workers._tick_machines(7.839)
	check(workers.records[0].step==0,"machine stage1 not early")
	workers._tick_machines(0.002)
	check(workers.records[0].step==1,"machine98 first phase")
	workers._tick_machines(11.76)
	check(workers.records[0].status=="identified" and not workers.records[0].quality,"machine two phases exact timing")
	var path:="user://v03_validation.dat"
	check(workers.save_to(path)==OK,"save v3")
	var restored:=M.new()
	check(restored.load_from(path),"load v3")
	check(restored.wallet.exact()==workers.wallet.exact() and restored.records==workers.records,"restore completed prices and stages")
	restored.scan_exposed_finds(); check(restored.wallet.exact()==workers.wallet.exact(),"no re-pay loaded drops")
	DirAccess.remove_absolute(path)
	# Synthetic v2 save exercises real migration and compatibility backup.
	workers.talents={"T00":true,"T11":true,"T12":true,"T21":true}; workers.knowledge=0
	workers.base_depth=6; workers.levels.power=0; workers.wallet=D.new("0")
	workers.save_to(path)
	var file:=FileAccess.open(path,FileAccess.READ); var data:Dictionary=file.get_var(false); file.close()
	data.version=2; data.erase("analyzer"); data.erase("queue_priority")
	file=FileAccess.open(path,FileAccess.WRITE); file.store_var(data); file.close()
	check(restored.load_from(path),"migrate v2")
	check(restored.knowledge==7 and restored.talents=={"T00":true},"refund changed branches")
	check(restored.levels.power==5 and restored.wallet.exact()=="0","migration restores viable digging without cash grant")
	check(restored.records[0].estimate==workers.records[0].estimate,"legacy price preserved")
	check(FileAccess.file_exists(path+".v2.bak"),"backup created")
	restored.save_to(path); restored.load_from(path)
	check(restored.knowledge==7,"migration refund not repeated")
	DirAccess.remove_absolute(path); DirAccess.remove_absolute(path+".v2.bak")
	print("EA_V03_MODEL: %d failure(s)"%failures); quit(1 if failures else 0)
