// Playback uses the actual PNG sequence, so edits preview immediately without re-encoding.
let frameTimer=null;
$('#dialog').addEventListener('close',()=>{clearTimeout(frameTimer);frameTimer=null});
function framesModal(id){const act=a(id),ex=last(act);if(!ex)return;const full=ex.meta.source_frames_available;const indices=full?Array.from({length:ex.meta.source_frame_count},(_,i)=>i):ex.meta.kept_source_indices;let excluded=new Set(act.options.excluded||[]),playing=false,cursor=0;let fps=(ex.meta.sample_fps||ex.meta.fps);
 const frameURL=i=>`${ex.base}/${full?'source_frames':'frames'}/${String(full?i:indices.indexOf(i)).padStart(3,'0')}.png`;
 modal('逐帧编辑 · '+act.name,`<p class="muted">按时间顺序提取，每秒 ${(ex.meta.sample_fps||ex.meta.fps)} 帧。勾选保留，取消即删除；预览即时更新。这里保留修正前的透明帧，应用后会按颜色设置重新检测。删帧后默认保持原时长，也可选择缩短时长。</p><div class="frame-compare"><div><small>输入视频（原速）</small><video id="sourceVideo" src="${esc(processSource(act)?.video||act.video||'')}" controls muted loop playsinline></video></div><div><small>原始透明帧 · 当前筛选</small><div class="dialog-preview checker"><img id="framePlayer" alt="当前透明帧"></div></div></div><div class="frame-controls"><button type="button" id="framePrev">上一帧</button><button type="button" id="framePlay">播放</button><button type="button" id="frameNext">下一帧</button><span id="frameCounter"></span></div><input id="frameScrub" type="range" min="0" max="${indices.length-1}" value="0" aria-label="帧时间轴"><div class="frame-controls"><button type="button" id="keepAll">全部保留</button><button type="button" id="keepHalf">隔帧保留（20 → 10 FPS）</button><label><input type="checkbox" id="preserveTime" checked> 保持片段时长</label><span id="frameSummary"></span></div><div class="frame-grid">${indices.map(i=>`<label class="frame-tile"><img loading="lazy" src="${frameURL(i)}" alt="第${i+1}帧"><span>#${i+1} · ${(i/(ex.meta.sample_fps||ex.meta.fps)).toFixed(2)}s</span><input type="checkbox" data-frame="${i}"></label>`).join('')}</div>${!full?'<p class="muted">此为旧版导出。请关闭窗口，在节点将 FPS 设为20并重新处理，以获得完整可恢复帧库。</p>':''}`,'<button type="button" data-close>取消</button><button type="submit" class="primary">应用并导出</button>',true);
 $('#framePlay').disabled=true;$('#framePlay').textContent='加载帧…';
 Promise.all(indices.map(i=>{const im=new Image();im.src=frameURL(i);return im.decode()})).then(()=>{if($('#framePlay')){$('#framePlay').disabled=false;$('#framePlay').textContent='播放'}}).catch(()=>notify('部分帧加载失败，请关闭后重新打开',true));
 const sequence=()=>indices.filter(i=>!excluded.has(i));
 const show=()=>{const i=indices[cursor];$('#framePlayer').src=frameURL(i);$('#frameCounter').textContent=`第 ${i+1} 帧${excluded.has(i)?'（已排除）':''}`;$('#frameScrub').value=cursor};
 const update=()=>{const seq=sequence();fps=$('#preserveTime').checked?seq.length/indices.length*(ex.meta.sample_fps||ex.meta.fps):(ex.meta.sample_fps||ex.meta.fps);$$('[data-frame]').forEach(el=>{el.checked=!excluded.has(Number(el.dataset.frame));el.closest('label').classList.toggle('excluded',!el.checked)});$('#frameSummary').textContent=`保留 ${seq.length}/${indices.length} 帧 · ${fps.toFixed(2)} FPS · ${(seq.length/(fps||1)).toFixed(2)} 秒`;show()};
 const tick=()=>{if(!playing||!$('#dialog').open)return;const seq=sequence();if(seq.length){const at=seq.indexOf(indices[cursor]);cursor=indices.indexOf(seq[(at+1)%seq.length]);show()}frameTimer=setTimeout(tick,1000/Math.max(fps,1))};
 $('#framePlay').onclick=()=>{playing=!playing;$('#framePlay').textContent=playing?'暂停':'播放';clearTimeout(frameTimer);if(playing)tick()};
 $('#framePrev').onclick=()=>{cursor=(cursor-1+indices.length)%indices.length;show()};$('#frameNext').onclick=()=>{cursor=(cursor+1)%indices.length;show()};$('#frameScrub').oninput=e=>{cursor=Number(e.target.value);show()};
 $$('[data-frame]').forEach(el=>el.onchange=()=>{el.checked?excluded.delete(Number(el.dataset.frame)):excluded.add(Number(el.dataset.frame));update()});
 $('#keepAll').onclick=()=>{excluded.clear();update()};$('#keepHalf').onclick=()=>{excluded=new Set(indices.filter((_,i)=>i%2));update()};$('#preserveTime').onchange=update;update();
 $('#dialogForm').onsubmit=async e=>{e.preventDefault();if(!sequence().length)return notify('至少保留一帧',true);try{await api('/actions/'+id,'PATCH',{options:{excluded:[...excluded],playback_fps:fps}});closeModal();await refresh();await processIds([id])}catch(err){notify(err.message,true)}};
};
