function upstreamImage(id){const edge=graph().edges.find(e=>e.to===(id==='reference'?'reference':'image-'+id)&&(e.slot||'source')==='source');return edge?imageItem(edge.from==='reference'?'reference':edge.from.slice(6)):null}
function imageModelLabel(id,kind='image'){
 const model=state.settings?.image_model||'未配置',job=state.jobs.find(j=>j.project===pid&&j.kind===kind&&(j.image_id===id||j.action===id));
 return `<div class="generation-model"><span>生成模型</span><strong>${esc(model)}</strong><small>使用连接设置中的图像模型</small>${job?.model?`<small>最近任务：${esc(job.model)}</small>`:''}</div>`;
}
function imageItems(){return p()?[p().base_image||{id:'reference',name:'Image',source:p().reference,prompt:''},...(p().images||[])]:[]}
function imageItem(id){return imageItems().find(im=>im.id===id)}
function connectedImage(id){const edge=graph().edges.find(e=>e.to==='action-'+id);return edge?imageItem(edge.from==='reference'?'reference':edge.from.slice(6)):null}
function imageRoute(id){return '/projects/'+pid+'/images/'+id}
function renderImageNodes(){return imageItems().map((im,i)=>{const legacy=im.id==='reference',key=legacy?'reference':'image-'+im.id;const pos=p().layout?.[key]||{x:45,y:95+i*480};return card(legacy?'reference':'image',key,pos,im.name||'Image','01 / IMAGE',`${imageModelLabel(im.id)}<div class="node-preview checker">${im.source?`<img src="${esc(im.source)}" alt="Image 图片">`:'<div class="empty-preview"><span>✧</span>文字生图 / 上传 / Ctrl+V 粘贴图片</div>'}</div><div class="node-meta"><span class="tag purple">Image</span><span class="tag">${esc(state.settings?.image_model)}</span></div><p class="node-prompt">${esc(im.prompt||'单独生成图片，或连接视频生成继续制作动画。')}</p><button data-image-command="upload" data-image-id="${im.id}">↑ 上传图片</button><button data-image-command="edit" data-image-id="${im.id}">✧ 生图 / 编辑</button><button data-image-command="green" data-image-id="${im.id}" ${im.source?'':'disabled'}>▧ 制作绿幕背景</button>${mediaDownload(im.source,im.name,'下载图片')}${statusHtml(jobFor(im.id,'image'),im.source?'图片已就绪 · 可连接视频生成':'等待图片')}`,im.id)}).join('')}
function renderImageInspector(){const im=imageItem(selected.aid||'reference')||imageItems()[0];if(!im)return;const upstream=upstreamImage(im.id);$('#inspectorBody').innerHTML=`<div class="eyebrow">IMAGE · ${esc(state.settings?.image_model)}</div><h2>Image</h2>${imageModelLabel(im.id)}<p class="muted">文字生图可以独立使用。图片输出可连接 Seedance 视频生成。</p><label class="field"><span>图片名称</span><input id="imageNodeName" value="${esc(im.name)}"></label>${im.source?`<div class="inspector-preview checker"><img src="${esc(im.source)}" alt="当前 Image"></div>${mediaDownload(im.source,im.name,'下载图片')}`:''}<button class="full" data-image-command="upload" data-image-id="${im.id}">↑ 上传图片</button><p class="muted">复制图片后，在画布按 Ctrl+V，会创建一个新的 Image 节点。文本框内粘贴仍作为文字输入。</p><label class="field"><span>生图 / 编辑提示词</span><textarea id="imageNodePrompt" placeholder="描述人物、怪物、道具、场景或其他图片…">${esc(typeof inlinePromptValue==='function'?inlinePromptValue('image',im.id,im.prompt):im.prompt)}</textarea></label><label class="field"><span>生成背景</span><select id="imageBackground"><option value="auto">根据提示词</option><option value="green">纯绿色背景（动画管线）</option><option value="transparent">透明背景（预览能力）</option></select></label><label class="checkfield"><input id="imageUseSource" type="checkbox" ${upstream?'checked':''} ${upstream?.source||im.source?'':'disabled'}> ${upstream?'使用上游 Image 作为参考：'+esc(upstream.name):'使用当前图片作为编辑参考'}</label>${upstream&&!upstream.source?'<p class="hint-box">上游图片尚未就绪，请先生成或上传。</p>':''}<button class="full primary" data-image-command="generate" data-image-id="${im.id}">✧ 生成图片</button><button class="full" data-image-command="green" data-image-id="${im.id}" ${im.source?'':'disabled'}>▧ 制作绿幕背景</button><div class="hint-box">透明 PNG 加绿底：本地处理。实色或复杂背景换绿幕：GPT 编辑，会使用 OpenAI API 额度。AI 编辑可能改变细节，生成后请检查。</div>`}
async function ensureImageProject(){if(p())return;const pr=await api('/projects','POST',{name:'图像工作流'});pid=pr.id;await refresh(true);setView('canvas')}
async function addImageNode(file){await ensureImageProject();const projectId=pid;const im=await api('/projects/'+projectId+'/images','POST',{name:file?.name?.replace(/\.[^.]+$/,'')||'Image'});if(file){const data=new FormData();data.append('file',file);await api('/projects/'+projectId+'/images/'+im.id+'/upload','POST',data)}const r=$('#viewport').getBoundingClientRect();await api('/projects/'+projectId,'PATCH',{layout:{...p().layout,['image-'+im.id]:{x:((r.width/2-transform.x)/transform.z-140),y:((100-transform.y)/transform.z)}}});selected={type:'image',aid:im.id};await refresh(true);notify(file?'图片已粘贴 / 导入画布':'Image 节点已创建')}
async function uploadNodeImage(id){const route=imageRoute(id)+'/upload',input=$('#fileInput');input.value='';input.accept='image/png,image/jpeg,image/webp';input.onchange=async()=>{if(!input.files[0])return;const data=new FormData();data.append('file',input.files[0]);try{await api(route,'POST',data);await refresh(true)}catch(err){notify(err.message,true)}};input.click()}
async function saveImageNode(id){if(!$('#imageNodePrompt'))return;await api(imageRoute(id),'PATCH',{name:$('#imageNodeName').value,prompt:typeof inlinePromptValue==='function'?inlinePromptValue('image',id,$('#imageNodePrompt').value):$('#imageNodePrompt').value})}
async function submitImageNode(id){await saveImageNode(id);if(!state.connection.openai)return settings();const body={prompt:typeof inlinePromptValue==='function'?inlinePromptValue('image',id,$('#imageNodePrompt').value):$('#imageNodePrompt').value,use_reference:$('#imageUseSource').checked,background:$('#imageBackground').value},route=imageRoute(id)+'/generate';modal('图像生成 · '+state.settings.image_model,'<p class="muted">将生成1张1024×1024 PNG，使用 OpenAI API 额度。只生成图片，不会自动提交 Seedance 视频任务。</p>','<button type="button" data-close>取消</button><button type="submit" class="primary">生成图片</button>');$('#dialogForm').onsubmit=async e=>{e.preventDefault();try{$('#dialogForm button[type=submit]').disabled=true;await api(route,'POST',body);closeModal();await refresh(true)}catch(err){notify(err.message,true);$('#dialogForm button[type=submit]').disabled=false}}}
async function greenImageNode(id){const route=imageRoute(id)+'/green';try{await api(route,'POST',{});await refresh(true);notify('已在本地添加纯绿底，未使用 API')}catch(err){if(!err.message.startsWith('需要AI换背景'))return notify(err.message,true);if(!state.connection.openai){notify('这张图没有透明背景，需要配置 GPT API 才能换背景',true);return settings()}modal('GPT 制作绿幕背景','<p class="muted">当前图片没有透明区域。将使用 GPT Image 2 编辑背景，产生 OpenAI API 费用。会要求保留主体，但仍需检查形状与颜色。</p>','<button type="button" data-close>取消</button><button type="submit" class="primary">制作绿幕图片</button>');$('#dialogForm').onsubmit=async e=>{e.preventDefault();try{$('#dialogForm button[type=submit]').disabled=true;await api(route,'POST',{allow_ai:true});closeModal();await refresh(true)}catch(error){notify(error.message,true);$('#dialogForm button[type=submit]').disabled=false}}}}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-image-command]');if(!b)return;const id=b.dataset.imageId;try{switch(b.dataset.imageCommand){case'edit':selected={type:id==='reference'?'reference':'image',aid:id};render(true);break;case'upload':await uploadNodeImage(id);break;case'generate':await submitImageNode(id);break;case'green':await greenImageNode(id);break}}catch(err){notify(err.message,true)}});
$('#inspectorBody').addEventListener('change',async e=>{if(['imageNodeName','imageNodePrompt'].includes(e.target.id)){try{await saveImageNode(selected.aid||'reference')}catch(err){notify(err.message,true)}}});
$('#addImage').onclick=()=>addImageNode().catch(e=>notify(e.message,true));
document.addEventListener('paste',e=>{if(e.target.closest('input,textarea,[contenteditable="true"]')||$('#dialog').open||view!=='canvas')return;const files=[...(e.clipboardData?.items||[])].filter(i=>i.kind==='file'&&i.type.startsWith('image/')).map(i=>i.getAsFile()).filter(Boolean);if(!files.length)return;e.preventDefault();(async()=>{for(const file of files)await addImageNode(file)})().catch(err=>notify(err.message,true))});
