function renderSheetNodes(){return (p()?.sheets||[]).map((s,i)=>{const row=p().actions.length+i,motion=sheetSource(s),ref=sheetReference(s),ex=last(s),out=sheetExport(s),preview=ex||motion?.original;let html='';if(s.source)html+=card('action','sheet-source-'+s.id,nodePosition('sheet-source-'+s.id,row,'action'),s.name+' · 原图','SPRITE SHEET / MOTION',`<div class="node-preview checker"><img src="${esc(s.source)}" alt="原版精灵图"></div><p>Sprite Sheet 动作输入</p>`,s.id);html+=card('process','sheet-edit-'+s.id,nodePosition('sheet-edit-'+s.id,row,'process'),'Sprite Sheet 改造','动作 + IMAGE + PROMPT',`${imageModelLabel(s.id,'sheet')}<div class="node-preview checker">${preview?`<img src="${preview.base}/preview.png" alt="精灵图动作预览">`:'<div class="empty-preview">连接 Sprite Sheet 动作输入</div>'}</div><p class="node-prompt">${esc(s.prompt)}</p><p class="muted">动作：${motion?'已就绪':'待连接 / 待上游处理'}<br>Image：${esc(ref?.name||'未连接，可仅用提示词修改')}</p><button data-command="sheet-edit" data-aid="${s.id}">编辑改造指令</button><button data-command="sheet-generate" data-aid="${s.id}" ${motion?'':'disabled'}>✧ 生成新版精灵图</button>${statusHtml(jobFor(s.id,'sheet'),ex?'新版已生成':'连接动作与外观参考后生成')}`,s.id);html+=card('export','sheet-export-'+s.id,nodePosition('sheet-export-'+s.id,row,'export'),'新版 Sprite Sheet','可继续连接下一次改造',`<div class="node-preview checker">${out?`<img src="${out.base}/spritesheet.png" alt="新版精灵图">`:'<div class="empty-preview">等待上游生成</div>'}</div>${out?`<a class="download" href="${out.base}/spritesheet.png" download>下载新版 PNG</a>`:''}<p class="muted">右侧端口可连接其他改造节点的动作输入。</p>`,s.id);return html}).join('')}
function renderRemixInspector(s){const motion=sheetSource(s),ref=sheetReference(s),preview=motion?.original;$('#inspectorBody').innerHTML=`<div class="eyebrow">SPRITE SHEET REMIX</div><h2>${esc(s.name)}</h2>${imageModelLabel(s.id,'sheet')}<p class="muted">上方输入：Sprite Sheet 动作。下方输入：Image 外观参考。程序按输入网格切图；AI 生成内容仍可能偏离网格。</p>${preview?`<div class="inspector-preview checker"><img src="${preview.base}/preview.png" alt="原版动作"></div><p class="muted">${motion.options.count} 帧 · ${motion.options.columns} 列 × ${motion.options.rows} 行</p>`:'<div class="hint-box">请把 Sprite Sheet 输出连接到此节点的动作输入。</div>'}${ref?.source?`<p class="muted">Image：${esc(ref.name)}</p><div class="inspector-preview checker"><img src="${esc(ref.source)}" alt="外观参考图"></div>`:'<p class="muted">可连接任意 Image 节点作为新外观参考。</p>'}<label class="field"><span>改造提示词</span><textarea id="sheetPrompt">${esc(s.prompt)}</textarea></label><button class="full" data-command="sheet-save" data-aid="${s.id}">保存提示词</button><button class="full primary" data-command="sheet-generate" data-aid="${s.id}" ${motion?'':'disabled'}>✧ 生成新版精灵图</button><button class="full" data-command="sheet-view" data-aid="${s.id}">原版 / 新版对比</button><p class="muted">整图改造属于实验功能：可能出现位置漂移、跨格、体型和颜色变化，无法保证逐帧动作一致。建议先用少量帧验证。</p>`}
sheetPreview=function(id){const s=sheet(id),motion=sheetSource(s),original=motion?.original,ex=last(s);modal('精灵图对比 · '+s.name,`<div class="field-row"><div><p>输入动作</p>${original?`<div class="dialog-preview checker"><img src="${original.base}/preview.png" alt="输入动作"></div>`:'等待上游'}</div><div><p>新版动作</p>${ex?`<div class="dialog-preview checker"><img src="${ex.base}/preview.png" alt="新版动作"></div><a class="download" href="${ex.base}/spritesheet.png" download>下载新版</a>`:'尚未生成'}</div></div>`,'<button type="button" data-close>关闭</button>',true);$('#dialogForm').onsubmit=e=>e.preventDefault()};
async function runVideoPipeline(id){
 const act=a(id),edge=graph().edges.find(e=>e.from==='action-'+id&&e.to.startsWith('process-'));
 const options=(edge?a(edge.to.slice(8)):act)?.options||{},count=options.target_frame_count||20;
 modal('一键生成 Sprite Sheet',`<label class="field"><span>Sprite Sheet 总帧数</span><input id="pipelineFrames" type="number" min="1" max="120" step="1" required value="${count}"></label><label class="field"><span>去绿幕强度</span><select id="pipelineStrength">${[[45,'温和 · 保留细节'],[25,'标准'],[12,'强力 · 清除残绿'],[5,'最强 · 默认']].map(([v,label])=>`<option value="${v}" ${v===(options.threshold??5)?'selected':''}>${label}</option>`).join('')}</select></label><p class="muted">帧数指整段动画的总帧数，保持原定截取时长。填入 1–120 的整数；可用帧不足时重复采样补足，导出总帧数与输入一致。强力去绿可能削弱细小边缘。</p>${act.video?'<p>使用当前视频，自动去绿幕、抽帧并导出，不重新生成视频。</p>':`<p class="cost-note">将使用 ${esc(videoModels[modelFor(act)]||modelFor(act))} 生成一段4秒原片，消耗 Seedance API 额度，然后自动截取、去绿幕并导出。</p>`}<p id="pipelineError" role="alert"></p>`,'<button type="button" data-close>取消</button><button type="submit" class="primary">确认并运行</button>');
 $('#dialogForm').onsubmit=async e=>{
  e.preventDefault();const button=$('#dialogForm button[type=submit]');if(button.disabled)return;button.disabled=true;
  try{
   if(!act.video){if(!state.connection.ark)throw Error('请先在连接设置中配置 Seedance');if(!connectedImage(id)?.source)throw Error('请先连接有图片的 Image 节点')}
   const spec={frame_count:Number($('#pipelineFrames').value),threshold:Number($('#pipelineStrength').value)};
   await flushInlinePrompts();await saveAction(id);
   const result=await api('/actions/'+id+'/pipeline','POST',spec);
   if(act.video)await api('/actions/'+result.process.slice(8)+'/process','POST');
   else await api('/actions/'+id+'/generate','POST',{auto_process:true});
   closeModal();await refresh(true);notify('已按所选设置开始制作 Sprite Sheet');
  }catch(err){$('#pipelineError').textContent=err.message;button.disabled=false}
 };
}
