const { chromium } = require('C:/Users/ruohaojing/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const { pathToFileURL }=require('node:url');
const path=require('node:path');
const fs=require('node:fs');
(async()=>{
 const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});
 const page=await browser.newPage({viewport:{width:1500,height:1000},deviceScaleFactor:1});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(pathToFileURL(path.join(__dirname,'dc-tree.html')).href);
 await page.waitForFunction(()=>document.getElementById('details').textContent.includes('D001'));
 const nodes=await page.locator('.node').count(),edges=await page.locator('.edge').count();
 if(nodes!==131||edges!==130) throw Error('Count mismatch');
 await page.screenshot({path:path.join(__dirname,'界面核验_起点.png')});
 await page.selectOption('#jump','D080');
 if(!(await page.locator('#details').innerText()).includes('青蛙帮手')) throw Error('Selection failed');
 if(await page.locator('.selected').getAttribute('data-id')!=='D080') throw Error('Highlight failed');
 await page.locator('#zoom').fill('70');await page.locator('#zoom').dispatchEvent('input');
 if(await page.locator('#zoomValue').innerText()!=='70%') throw Error('Zoom failed');
 await page.screenshot({path:path.join(__dirname,'界面核验_分叉.png')});
 await page.click('#start');
 if(await page.locator('.selected').getAttribute('data-id')!=='D001') throw Error('Start failed');
 await page.setViewportSize({width:1750,height:1750});
 await page.locator('#zoom').fill('35');await page.locator('#zoom').dispatchEvent('input');
 await page.locator('#viewport').evaluate(e=>e.scrollTo(0,0));
 await page.screenshot({path:path.join(__dirname,'总图核验.png')});
 const result={nodes,edges,selection:true,zoom:true,return_to_start:true,script_errors:errors};
 fs.writeFileSync(path.join(__dirname,'界面校验.json'),JSON.stringify(result,null,2));
 console.log(JSON.stringify(result));await browser.close();if(errors.length)process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
